In [1]:
docA = "the cat sat on my face"
docB = "the dog sat on my bed"

In [2]:
bowA = docA.split(" ")
bowB = docB.split(" ")


In [3]:
words = set(bowA).union((bowB))
words

{'bed', 'cat', 'dog', 'face', 'my', 'on', 'sat', 'the'}

In [58]:
a = [1,2,3,1,2,3]
aa = dict.fromkeys(a,0)
for i in a:
    aa[i]+=1
aa

{1: 2, 2: 2, 3: 2}

In [4]:
worddictA = dict.fromkeys(words,0)
worddictB = dict.fromkeys(words,0)

In [5]:
print(worddictA)
print(worddictB)

{'face': 0, 'my': 0, 'dog': 0, 'the': 0, 'cat': 0, 'sat': 0, 'bed': 0, 'on': 0}
{'face': 0, 'my': 0, 'dog': 0, 'the': 0, 'cat': 0, 'sat': 0, 'bed': 0, 'on': 0}


In [6]:

for word in bowA:
    worddictA[word]+=1
for word in bowB:
    worddictB[word]+=1

In [7]:
print(worddictA)
print(worddictB)

{'face': 1, 'my': 1, 'dog': 0, 'the': 1, 'cat': 1, 'sat': 1, 'bed': 0, 'on': 1}
{'face': 0, 'my': 1, 'dog': 1, 'the': 1, 'cat': 0, 'sat': 1, 'bed': 1, 'on': 1}


In [8]:
import pandas as pd


In [9]:
df = pd.DataFrame([worddictA,worddictB])
df

bed  cat  dog  face  my  on  sat  the
0    0    1    0     1   1   1    1    1
1    1    0    1     0   1   1    1    1

## count vectorizer


In [10]:
import numpy as np
import pandas as pd
from  sklearn.feature_extraction.text import CountVectorizer
from sklearn.cross_validation import train_test_split
from  sklearn.naive_bayes import MultinomialNB
import warnings
warnings.filterwarnings('ignore')

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [11]:
import nltk

In [12]:
df = pd.read_csv('spamham',sep='\t',names=['Status','message'])

In [13]:
df.head()

Status                                            message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
len(df),len(df[df.Status =='ham'])

(5572, 4825)

In [15]:
df.loc[df['Status'] == 'ham','Status'] = 1
df.loc[df['Status'] == 'spam','Status'] = 0

In [16]:
df.head()

Status                                            message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [17]:
X = df['message']
y = df['Status']

In [18]:
cv = CountVectorizer()

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=4)

In [20]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [21]:
X_traincv = cv.fit_transform(["hey how are you?","where are you from?","i'm moving to delhi"])


In [22]:
X_traincv.toarray()

array([[1, 0, 0, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0]], dtype=int64)

In [23]:
cv.get_feature_names()

['are', 'delhi', 'from', 'hey', 'how', 'moving', 'to', 'where', 'you']

In [24]:
cv1 = CountVectorizer()

In [25]:
X_traincv = cv1.fit_transform(X_train)

In [26]:
a = X_traincv.toarray()
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [28]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'me', 'now',
        'online', 'or', 'replying', 'sleeping', 'spys', 'take', 'to', 'wat',
        'you'],
       dtype='<U27')]

In [29]:
len(a[0])

7762

In [30]:
X_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

## TFIDF

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer,TfidfTransformer

In [32]:
cv = TfidfVectorizer(stop_words='english',min_df=1)

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=4)

In [34]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4457,), (1115,), (4457,), (1115,))

In [35]:
X_traincv = cv.fit_transform(["hey how are you?","where are you from?","i'm moving to delhi"])


In [36]:
X_traincv.toarray()

array([[ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

In [37]:
cv.get_feature_names()

['delhi', 'hey', 'moving']

In [38]:
cv1 = TfidfVectorizer(min_df=1,stop_words='english')

In [39]:
X_traincv = cv1.fit_transform(X_train)

In [40]:
a = X_traincv.toarray()
a

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.19618715,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [41]:
a[0]

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [42]:
cv1.inverse_transform(a[0])

[array(['checking', 'going', 'got', 'haha', 'lor', 'mails', 'online',
        'replying', 'sleeping', 'spys', 'wat'],
       dtype='<U27')]

In [43]:
len(a[0])

7498

In [44]:
X_train.iloc[0]

'U sleeping now.. Or you going to take? Haha.. I got spys wat.. Me online checking n replying mails lor..'

### model

In [45]:
mnb = MultinomialNB()

In [46]:
y_train = y_train.astype('int')

In [47]:
mnb.fit(X_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [48]:
X_testcv  = cv1.transform(X_test)

In [49]:
prd = mnb.predict(X_testcv)
prd

array([1, 1, 1, ..., 1, 1, 0])

In [50]:
actual = np.array(y_test)

In [51]:
count = 0
for i in range(len(actual)):
    if actual[i]==prd[i]:
        count+=1

In [52]:
count

1068

In [53]:
len(prd)

1115

In [54]:
1068/1115.0

0.957847533632287